name: Sync Labels to Repositories

on:
  workflow_dispatch:
    inputs:
      repositories:
        description: 'Comma-separated list of target repositories (repo1,repo2)'
        required: true
        default: ''

jobs:
  sync-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install github-label-sync
        run: npm install -g github-label-sync

      - name: Sync labels to multiple repositories
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_LABEL_SYNC }}
        run: |
          IFS=',' read -ra REPOS <<< "${{ github.event.inputs.repositories }}"
          for REPO in "${REPOS[@]}"; do
            echo "➡️ Syncing labels to jetbrains-eval-lab/$REPO"
            github-label-sync --access-token "$GITHUB_TOKEN" --labels .github/labels.json "jetbrains-eval-lab/$REPO"
          done
